global using System.Diagnostics;
global using System.Net.WebSockets;
global using System.Text;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Web;
global using Script.Bypasses;
global using Script.Scrapers.NSFW;
global using Script.Util;
global using Script.Util.Expanders;
global using Script.Util.FileUtil;
global using Script.Util.RegexUtil;
global using static Script.Util.FileUtil.FileMethods;
global using static Script.Util.Expanders.Parsing;
global using static Script.Util.Expanders.MiscExpanders;
global using static Script.Util.Expanders.StringExpander;
global using static Script.Util.Expanders.ShittyMethods;